In [10]:
import os 
import pandas as pd
import glob

all_data = []
for f in glob.glob("/Users/javi/Desktop/Python/LALIGA/*.xlsx"):
    all_data.append(pd.read_excel(f))
    
df = pd.concat(all_data, ignore_index=True)

writer = pd.ExcelWriter('final.xlsx')
df.to_excel(r"/Users/MoritzPfeifer/Documents/LALIGA/Libro.xlsx", index = False)
writer.save()

/Users/MoritzPfeifer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

In [9]:
df

,AwayTeam,Date,Div,FTAG,FTHG,FTR,HomeTeam,Time,Unnamed: 8
0,Ath Bilbao,2010-08-28,SP1,1,0,A,Hercules,NaN,NaN
1,Sevilla,2010-08-28,SP1,4,1,A,Levante,NaN,NaN
2,Valencia,2010-08-28,SP1,3,1,A,Malaga,NaN,NaN
3,Getafe,2010-08-29,SP1,1,3,H,Espanol,NaN,NaN
4,Zaragoza,2010-08-29,SP1,0,0,D,La Coruna,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6075,Ath Bilbao,2020-07-19,SP1,0,4,H,Granada,20:00:00,no
6076,Real Madrid,2020-07-19,SP1,2,2,D,Leganes,20:00:00,no
6077,Getafe,2020-07-19,SP1,0,1,H,Levante,20:00:00,no
6078,Mallorca,2020-07-19,SP1,2,2,D,Osasuna,20:00:00,no
6079,Valencia,2020-07-19,SP1,0,1,H,Sevilla,20:00:00,no